export const CATEGORIES = [
    { nameImg: 'transport', value: 'транспорт', label: 'Транспорт', type: 'costs' },
    { nameImg: 'products', value: 'продукты', label: 'Продукты', type: 'costs'},
    { nameImg: 'health', value: 'здоровье', label: 'Здоровье', type: 'costs' },
    { nameImg: 'alcohol', value: 'алкоголь', label: 'Алкоголь', type: 'costs' },
    { nameImg: 'entertainment', value: 'развлечения', label: 'Развлечения', type: 'costs' },
    { nameImg: 'home', value: 'всё для дома', label: 'Всё для дома', type: 'costs' },
    { nameImg: 'tech', value: 'техника', label: 'Техника', type: 'costs' },
    { nameImg: 'com-payment', value: 'коммуналка, связь', label: 'Коммуналка, связь', type: 'costs' },
    { nameImg: 'hobby', value: 'спорт, хобби', label: 'Спорт, хобби', type: 'costs' },
    { nameImg: 'education', value: 'образование', label: 'Образование', type: 'costs' },
    { nameImg: 'other', value: 'прочее', label: 'Прочее', type: 'costs' },
    { nameImg: 'salary', value: 'ЗП', label: 'ЗП', type: 'income' },
    { nameImg: 'other-income', value: 'доп. доход', label: 'Доп. доход', type: 'income' },
]
